### ISSUE TITLE
Conflict between APO and Wordfence

### ISSUE THREAD

**Issue by bryanesler** [cloudflare/Cloudflare-WordPress#297]
Activating APO locks out all users from the admin, even those with whitelisted IP's in Wordfence. Deactivating APO and purging cache works fine.

**Comment by lkraav** [comment]
We are seeing all incoming WooCommerce Orders have the same Customer IP.

This seems like something is broken / changed with APO and how it transmits proxy vs original IP information?

**Comment by garrettgalow** [comment]
We are aware of issues with APO and properly sending the ip. We are working on a fix. This won't change the plugin at all since the issue happens in our edge. We will close this when a fix is released, but you won't see any PR.

**Comment by MauriceW2** [comment]
We're having the same issue and diabled APO. It is fixed? What do we need to do?

**Comment by rneveri** [comment]
@MauriceW2 probably not fixed yet. Since this issue is still "Open"

**Comment by garrettgalow** [comment]
rneveri is right. This is not yet resolved, but I will update the issue once we have rolled out a fix.

**Comment by garrettgalow** [comment]
We just finished rolling out a fix, so please verify that IPs are correctly being populated now. This was a change to the service on the edge, so no plugin changes or update.

**Comment by rneveri** [comment]
Thanks @garrettgalow for the fix and the update. I already see a confirmation of the fix on the community page, I'll check later  at night when the traffic calms :)

**Comment by rneveri** [comment]
@garrettgalow Seems fine now! Thanks 👍

**Comment by MauriceW2** [comment]
Works here too. Thank you all!

**Comment by mmalferov** [comment]
Time from time I see IPs IPv6, as example today, nov 15 2020 at 9:01 GMT 0: 2a00:1fa0:463:d978:875:c067:a882:dc04. A last 24 hours i see IPv4 addresses, but sometime IPv6. Apparently, the problem with displaying real IP addresses is not completely solved.
