### ISSUE TITLE
APO not clearing pagination cache when posts are created

### ISSUE THREAD

**Issue by scottbuscemi** [cloudflare/Cloudflare-WordPress#337]
When a new post is added, blog pagination (ie `/page/2/` or `/page/3/`) cache is not being cleared automatically. Clearing the Cloudflare cache manually resolves this issue.

**Comment by orenwolf** [comment]
👍 confirmed. We see the same issue and currently work around it with page rules.

**Comment by scottbuscemi** [comment]
@orenwolf How are you configuring the Page Rules to combat this?

**Comment by orenwolf** [comment]
We've created a rule for "*example.com/page/*" with an Edge Cache TTL set to 30 minutes.

This is suboptimal, as it delays the pagination caches by up to 30 minutes when changes occur, but it's much better than the default 30 days!

**Comment by scottbuscemi** [comment]
As a business customer, we can only set down to 1 hour.. That's quite a long time to have the wrong pagination cached for our blog.

I'll see if I can get some Cloudflare eyeballs on this :)

**Comment by orenwolf** [comment]
We’re business customers and can set to 30m, you may wish to double-check.

**Comment by scottbuscemi** [comment]
My mistake - we downgraded to "Pro" so only 60m.

**Comment by phansheng89** [comment]
The same issue happen for Single post Pagination, the sub page cache is not cleared automatically!

**Comment by sejoker** [comment]
FYI we will try to get the fix out early next week.

**Comment by scottbuscemi** [comment]
Thanks @sejoker - looking forward to it.

**Comment by thanks2music** [comment]
@sejoker Thanks for the great WordPress plugin.

I have a similar problem besides pagination.

1. new posts on the top page are not updated when viewed with a real browser on a smartphone (no problem with desktop browsers)
2. the category and tag pages to which the article belongs are not updated anymore.
3. when I update a published article with an addition, the actual browser on my smartphone does not update as in 1.

I am having trouble with the following three points.

I'm sorry to bother you, but I would appreciate it if you could check this for me.
Thank you very much.

**Comment by garrettgalow** [comment]
Reopening this since we reverted the fix as it caused performance regressions

**Comment by fidividi32** [comment]
Hi guys any update on this?
After weeks of investigating, we realized our issue is precisely this one, and our WordPress APO enabled website is sitting on CloudFlare with this issue causing angry customer/users due to old posts appearing on subsequent category pages. Thanks for any updates.

**Comment by sejoker** [comment]
@fidividi32 please use the described workaround of *example.com/page/* with an Edge Cache TTL set to 30 minutes. We plan to rollout the fix that will do the same logic automatically without a need of page rule.

**Comment by fidividi32** [comment]
> @fidividi32 please use the described workaround of _example.com/page/_ with an Edge Cache TTL set to 30 minutes. We plan to rollout the fix that will do the same logic automatically without a need of page rule.

Hi,
Thank you for your reply.

1) our articles on this busy blog website get updated sometimes as quick as 2~3 minutes, edge cache TTL of 30 minutes means a whole bunch of articles will be missing within that 30 minute update window, i.e. the paginated pages will be out-of-date for a football website that reports live matches...
2) Also, we're an APO paying customer, we're not on a paid CloudFlare plan so if 30 minutes even possible?

**Comment by Plinpod** [comment]
For those that are using the Page Rule workaround, how are you combating the pagination on the category archive pages for each post?

*example.com/category/some-category/page*

**Comment by sejoker** [comment]
> > @fidividi32 please use the described workaround of _example.com/page/_ with an Edge Cache TTL set to 30 minutes. We plan to rollout the fix that will do the same logic automatically without a need of page rule.
> 
> Hi,
> Thank you for your reply.
> 
> 1. our articles on this busy blog website get updated sometimes as quick as 2~3 minutes, edge cache TTL of 30 minutes means a whole bunch of articles will be missing within that 30 minute update window, i.e. the paginated pages will be out-of-date for a football website that reports live matches...
> 2. Also, we're an APO paying customer, we're not on a paid CloudFlare plan so if 30 minutes even possible?

We released a change that will set Edge Cache TTL to 30 mins for example.com/page/* by default.

**Comment by scottbuscemi** [comment]
This doesn't resolve much at all, which still makes APO a no-go for my sites. It seems category and tag pagination aren't covered by this? ie `/category/:name/page/2`

Would it be possible for the plugin itself to just pass all the pagination wildcards to Cloudflare systems, then the APO system itself knows what to clear based off of that? Rather than iterating through the pages on the client-side?

**Comment by sejoker** [comment]
> Would it be possible for the plugin itself to just pass all the pagination wildcards to Cloudflare systems, then the APO system itself knows what to clear based off of that? Rather than iterating through the pages on the client-side?

I don't think it's feasible at the moment.

**Comment by scottbuscemi** [comment]
Should I create another issue for category pagination? This isn't resolved...

**Comment by jacobbednarz** [comment]
Sure, it seems to be different enough to the initial issue that we
should track it separately (especially considering part of the response
is that it’s not feasible at the moment)
