### ISSUE TITLE
APO cache is not cleared properly.

### ISSUE THREAD

**Issue by rvola** [cloudflare/Cloudflare-WordPress#404]
### Confirmation

My issue isn't already found on the issue tracker.
I have replicated my issue using the latest version of the plugin and it is still present.

### WordPress version

5.7

### Cloudflare-WordPress version

4.4.0

### PHP version

7.4.0

### Expected result

that the APO cache after a change / publish / etc really clears

### Actual result

Only the desktop version cache is cleared

### Steps to reproduce

Activate the plugin
Activate APO
Activate "Cache by device type"
Create content.
View the page with mobile and desktop (the order does not matter).
Publish new content.
Top up on mobile (nothing has changed: no new content)
Reload on desktop (new content appears)

### Additional factoids

I investigated the problem at length and here are my conclusions.

When the "[zonePurgeFiles](https://github.com/cloudflare/Cloudflare-WordPress/blob/f87045b0227de24e57af4d4d88d88583afa0468d/src/WordPress/WordPressClientAPI.php#L59)" method is executed with an array of 30 lines, it clears the cache well but not in mobile (tablet I have not checked).

I modified the request by adding the headers "CF-Device-Type" but nothing changes.

If I delete the url in the Cloudflare interface directly it clears all the caches on that page.

If I modify the request not to send an array but just 1 url like this (imagining that the first line $files[0] is my test url 😉):

```
$request = new Request('DELETE', 'zones/'.$zoneId.'/purge_cache', array(), array('files' => $files[0]));
$response = $this->callAPI($request);
```
the cache clears well.

Looks like the request by array does not clear the devicetype cache

**Comment by rvola** [comment]
similary #394

**Comment by rvola** [comment]
here is some additional feedback.

I need to use mobile / desktop cache unbundling despite my site being responsive, there is an ad script that can't work properly.

I also use before activating APO the plugin WP-ROCKET with options:

- [x] Enable caching for mobile devices
- [x] Separate cache files for mobile devices

I did a test:

1. Clear all WP-Rocket cache
2. Clear all Cloudflare cache
3. Load the home on the desktop (WP-ROCKET OK / Cloudflare OK file)
4. Load the home on the mobile (WP-ROCKET OK / Cloudflare OK file)
5. Creation of a new article
6. WP Rocket erases index-https.html (with gzip too) and index-mobile-https.html (with gzip too)
7. Loading the page on desktop: OK Cloudlfare updated with the 'age' header
8. Loading of the page on mobile: KO Cloudflare does not give a new version
9. Verification of the WP-Rocket cache folder: the index-https.html file has been successfully recreated but not the mobile one.

The problem really comes from the side of Cloudflare which does not delete the "mobile" file with the API

**Comment by girirajnet** [comment]
I'm also facing the same problem . Pls.fix it

**Comment by girirajnet** [comment]
Is anyone working on this issue? A month has crossed.

**Comment by garrettgalow** [comment]
"9. Verification of the WP-Rocket cache folder: the index-https.html file has been successfully recreated but not the mobile one."

If I understand this correctly, if WP-rocket cache doesn't update the mobile file then Cloudflare is going keep caching that old file provided by WP-rocket.

**Comment by rvola** [comment]
No, Rocket does not generate a mobile file because Cloudflare's cache "responds before reaching the server".
The problem comes from the Cloudflare purge which does not take place.

Look at the headers in particular the "Age" and you will see that the mobile version is older than the computer version.

The problem seems to really come from the Cloudflare API

**Comment by girirajnet** [comment]
@rvola If Cloudflare API key is the issue, do we need to update / change the key?

If yes how do we update the new API key in the Wordpress plugin?

**Comment by rvola** [comment]
sorry I made myself misunderstood.
This is not CloudFlare's key to the problem.
It is the API command which does not clear ALL the cache of the page

**Comment by girirajnet** [comment]
OK. Can we do anything from our side or only Cloudflare can help?

**Comment by rvola** [comment]
I do not know.
I put a hypothesis, tried to redo my test protocol to know if it comes from the plugin.

**Comment by girirajnet** [comment]
Thank You. 

Pls update here if you got the solution.

**Comment by rvola** [comment]
for my part I have no solution.
If the authors of the plugin can look, it would appeal to everyone

**Comment by imukesh1337** [comment]
It's really annoying! Crawlers are not even considering new content because of this issue. Earlier I was using WP Rocket but now I shifted to LITESPEED Cache the problem is same and that means it is directly from Cloudflare APO

**Comment by rvola** [comment]
Hello,
Could a moderator escalate the problem to the Cloudflare API Team?

**Comment by girirajnet** [comment]
I have explained in their forum too https://community.cloudflare.com/t/apo-cache-is-not-clearing-properly/274355

**Comment by rvola** [comment]
thanks @girirajnet

**Comment by petr00kos** [comment]
Exact same issue here with LSCache + Cloudflare APO. 

Cloudflare Cache By Device Type = enabled
LSCache Mobile Cache = enabled

Expected result
that the APO cache after a change / publish / etc clears & updates for all types of devices

Actual result
Only the desktop version cache is cleared

**Comment by sejoker** [comment]
I had a look at APO purge issue when "Cache By Device Type" is enabled. I can't reproduce the issue without more details ( purging of all variants works fine on our test setup).

There is a Cloudflare Purge API quirk for  "Cache By Device Type": when the purge happens it only purges for 1 particular device type variant not all of them. So internally APO team supports additional infrastructure to listen to Purge requests, detects "Cache By Device Type" and purges the remaining variations. I hope this explains why there is no special treatment of "Cache By Device Type" in the WordPress plugin.

**Comment by coolrecep** [comment]
OMG, I thought I was the only one waiting for two months to get this fixed. Having the exact same issue. We even removeed LSCache and the issue is still there.

**Comment by coolrecep** [comment]
OH, BTW Cloudflare is aware of the issue and they are looking into it.

> Thanks for following up.
> 
> I fully understand the frustration that this is taking longer than expected to get addressed. As this issue is now escalated, I expect to have product engineering team investigating potential root cause of your report and similar issues shortly.
> 
> When we have a new update for you, we will let you know straight away. We appreciate your patience whilst we are working on this.
> 
> Sincerely,

**Comment by girirajnet** [comment]
Cloudflare support team is giving the same answer for past 2 months :-) . Hope they will solve it soon.

**Comment by coolrecep** [comment]
Actually for the past 2 months I was receiving the "we are looking into it" answer. They have now acknowledged it and working on a fix. That's what I have been told.

**Comment by girirajnet** [comment]
Thank You for the update. We have been waiting so long.

**Comment by coolrecep** [comment]
Tell me about it...

![image](https://user-images.githubusercontent.com/13221472/124285884-0ce67680-db57-11eb-8bd6-0dfa79626f74.png)

**Comment by coolrecep** [comment]
And this was the first ticket where they couldn't find the problem.

**Comment by sejoker** [comment]
I released a changed that could have fixed the issue, please test it out.

**Comment by petr00kos** [comment]
Not resolved after testing, still Only the desktop version cache is cleared

**Comment by coolrecep** [comment]
Are you working at CF? This is probably a server side issue. Nothing to do with plugin, though a cron job may be applied.

**Comment by girirajnet** [comment]
> I had a look at APO purge issue when "Cache By Device Type" is enabled. I can't reproduce the issue without more details ( purging of all variants works fine on our test setup).
> 
> There is a Cloudflare Purge API quirk for "Cache By Device Type": when the purge happens it only purges for 1 particular device type variant not all of them. So internally APO team supports additional infrastructure to listen to Purge requests, detects "Cache By Device Type" and purges the remaining variations. I hope this explains why there is no special treatment of "Cache By Device Type" in the WordPress plugin.

Earlier mobile and desktop version **VIEW** were conflicting, so we were getting Desktop view in mobile and mobile view in desktop.

then Cloudflare has released **Cache By Device Type**, and it has solved the **VIEW** conflicting, but after that if we made any changes in the existing article or created an article, the cache is updating only in desktop version but not mobile.

This is the problem everyone is facing / complaining now. Hope CF will take serious action on this.

Thank You
Giri

**Comment by sejoker** [comment]
Unfortunately the change was reverted due to increased load on Cache purge infrastructure. We will engage with Cache and API team to find a solution for this issue.

**Comment by sejoker** [comment]
If you would like to beta test the potential fix on your site please DM me at https://community.cloudflare.com/u/yevgen with the details. I will be able to enable the change specifically for the selected domains.

**Comment by coolrecep** [comment]
I logged in but could not find a button to start a conversation...

**Comment by girirajnet** [comment]
> If you would like to beta test the potential fix on your site please DM me at https://community.cloudflare.com/u/yevgen with the details. I will be able to enable the change specifically for the selected domains.

I haven't renewed the APO subscription again due to cache issue. Hope @coolrecep is working with you.

If you need help let us know.. will renew again and check.

**Comment by coolrecep** [comment]
I'm a PRO custome but I can not PM him. Go figure...

**Comment by girirajnet** [comment]
> I'm a PRO customer but I can not PM him. Go figure...

Me too don't know how to DM.

@sejoker can you explain to us how to do? We would like to fix the issue ASAP.

**Comment by sejoker** [comment]
FYI @coolrecep I've started a thread at https://community.cloudflare.com.

**Comment by coolrecep** [comment]
I could not find it either. Link to the thread please.

**Comment by coolrecep** [comment]
Where is the thread? I've crawled through your posts and found none. Be specific please!

**Comment by sejoker** [comment]
My bad, I created a new private conversation here: https://community.cloudflare.com/t/apo-cache-purge-issues/291140

**Comment by coolrecep** [comment]
Your fix does not seem to be working @sejoker 

![image](https://user-images.githubusercontent.com/13221472/127975553-fd6eb505-dffd-413d-bdcf-fef92f34cdb4.png)

**Comment by sejoker** [comment]
@coolrecep answered in https://community.cloudflare.com/t/apo-cache-purge-issues/291140.

**Comment by girirajnet** [comment]
@coolrecep if you get update and if its worth Pls share here. Thank You

**Comment by coolrecep** [comment]
> @coolrecep if you get update and if its worth Pls share here. Thank You

Not working for me right now but I'm sure we'll figure it out.

**Comment by girirajnet** [comment]
> > @coolrecep if you get update and if its worth Pls share here. Thank You
> 
> Not working for me right now but I'm sure we'll figure it out.

Thank You @coolrecep for the update. If it's working, Pls don't forget to update here :-)

**Comment by Joshua-James-AU** [comment]
Any update please @sejoker 
Is there anything to beta test? My sites have 50% mobile views so it's sort hurting not having the mobile cache not working as I am sure many others are in the same boat. 
Thanks for reading.

**Comment by coolrecep** [comment]
It's working fine now. Informed @sejoker as well.

**Comment by Joshua-James-AU** [comment]
> It's working fine now. Informed @sejoker as well.

Awesome to hear, do we need to wait for a plugin update or is the fix live now on the backend with cloudflare? 

Thanks for sharing

**Comment by girirajnet** [comment]
> It's working fine now. Informed @sejoker as well.

Thank You @coolrecep for your update.

Will check

**Comment by coolrecep** [comment]
I'm sorry to inform you that I came back to Istanbul and it seems that the issue persists. I tried on my mobile right now and contents are 9 days old!

When I was on another province I tried with Chrome incognito mode with mobile profile, it was working Fine. Back to square one.

I'll keep communicating with @sejoker

**Comment by girirajnet** [comment]
> I'm sorry to inform you that I came back to Istanbul and it seems that the issue persists. I tried on my mobile right now and contents are 9 days old!
> 
> When I was on another province I tried with Chrome incognito mode with mobile profile, it was working Fine. Back to square one.
> 
> I'll keep communicating with @sejoker

Yes . Its not working 🙁.

Pls update once you got the solution from @sejoker

**Comment by petr00kos** [comment]
@sejoker do we have any updates please ? The problem with Purging Cache when "Cache by device type" is enabled still persists

**Comment by Joshua-James-AU** [comment]
@sejoker please any news?

**Comment by coolrecep** [comment]
Disabling Cache By Device Type solves the problem but this time, mobile version of the site is served even in desktop mode.

Cloudflare rep sent me an email last week, I told them about this problem and no reply yet...

It has been a year god damn it! I'm being helpful here but you are not providing any fix. I have provided all the information you need.

**Comment by Joshua-James-AU** [comment]
> Disabling Cache By Device Type solves the problem but this time, mobile version of the site is served even in desktop mode.
> 
> Cloudflare rep sent me an email last week, I told them about this problem and no reply yet...
> 
> It has been a year god damn it! I'm being helpful here but you are not providing any fix. I have provided all the information you need.

Yeah the cache by device is what I did but it aint ideal, if we been waiting a year already then I am stopping all my subs next month which I got several, finding a better solution its a shame but this ain't good enough, cloudflare too big don't care, it's what happens sadly.

**Comment by girirajnet** [comment]
> Disabling Cache By Device Type solves the problem but this time, mobile version of the site is served even in desktop mode.
> 
> Cloudflare rep sent me an email last week, I told them about this problem and no reply yet...
> 
> It has been a year god damn it! I'm being helpful here but you are not providing any fix. I have provided all the information you need.

@coolrecep When APO introduced the desktop and mobile version conflict issue was there and many complained then only they introduced "Cache by device type" which is solved the cache (desktop version in mobile and mobile version in desktop) conflict problem, but after that mobile version cache is not updating which we are all facing the issue now and complaining.

If we logged in to our account it's showing the updated cache version, but if we are checking the site without logged in then it's not showing the updated version.

Even If anyone is commented in the article, it's not showing the comment, so we have to clear the particular article cache then only it will be visible to all.

I'm not sure why CF is taking so much time to fix the issue. If it's a free service means we may not force them to do, but it's a paid service but still they don't care about it. 

Even I have raised two tickets and explained everything and many like you explained and supported but no response.

It's really disappointed and frustrating.

**Comment by coolrecep** [comment]
Can't sign up B/C it's a part of APO.

https://blog.cloudflare.com/automatic-signed-exchanges/

**Comment by girirajnet** [comment]
> I hear the frustration (well earned) from you folks. At the moment our team is resource-limited and fully preoccupied with launching Cloudflare Images product. We are actively hiring to expand APO team so hopefully in September/October we be in the position to address purging issues for "Cache By Device Type" and extend APO functionality further (better caching rate, support for `cdn-cache-control` etc.)

Hello @sejoker Hope the Cloudflare Images has been implemented.

Now the October first week. We are expecting to solve the cache issue. Its difficult to clear the cache every time and proceed.

Can you Pls look in to the issue?

Thanks
Giri

**Comment by girirajnet** [comment]
> @girirajnet thanks for flagging this. The fix will work out of box for new customers who will activate APO "Cache by Device Type". For existing customers the additional step is necessary:
> 
> * after the upgrade to 4.6.0 please navigate APO card in Cloudflare plugin and make sure APO "Cache by Device Type" is activated.
> * after that any new content change should send purge requests both on desktop and mobile devices.
> 
> I recommend purge all Cache once to make sure you content is in sync for desktop and mobile variants.
> 
> @girirajnet please tell more:
> 
> * Do you have "Purge cache on mobile" enabled?
> * Have you navigated to APO card in the plugin?
> * Have you purged all cache (won't be necessary in all cases, but probably worth it to do once)?
> * Do you experience a different use case as @rvola originally described? It could be an additional use case we need to look into.

Hello @sejoker 

Here are my answers 

"Do you have "Purge cache on mobile" enabled?"

I don't have this option. I have options only "Purge Everything and Purge Individual files"

"Have you navigated to APO card in the plugin?"

Yes.

"Have you purged all cache (won't be necessary in all cases, but probably worth it to do once)?"

Yes. I have done in from APO plugin and web interface too.

"Do you experience a different use case as @rvola originally described? It could be an additional use case we need to look into"

The changes are updating properly in the desktop but not in mobile. This is the issue.

After complete purge, I made changes in the article but the changes reflecting in desktop but not in mobile. If I purge a particular article link then it's showing mobile too.

@coolrecep Happy to hear that the issue is resolved for you but am not sure why its not working for me.

Thanks
Giri

**Comment by coolrecep** [comment]
You may need to post an article or clear the cache if there is any. That was the solution for us at least.

**Comment by sejoker** [comment]
> Do you have "Purge cache on mobile" enabled?

@girirajnet  I meant APO's "Cache By Device Type" option enabled?

> If I purge a particular article link then it's showing mobile too.

This is suspicious, by default the purge only applies to desktop variant. It could be unrelated to the issues discussed here.

What mobile device you use for testing?

**Comment by girirajnet** [comment]
> Cache By Device Type

Yes @sejoker Cache By Device Type is enabled.

Particular article means its an example link only.

I have tested a few other articles as well. The changes are reflecting properly in mobile for the first time, but if I update the article again, it's not showing the updated version.

it works only for first attempt. I'm not sure should I change anything the settings?

Browser Cache TTL I set as 2 minutes.

I'm using OnePlus 8 and I checked in my friend mobile too. Tried different browsers and with private mode. Looks same.

**Comment by sejoker** [comment]
could you send an User-Agent header you have in OnePlus 8?

**Comment by sejoker** [comment]
There are plenty of sites that can show it, for example: https://whatmyuseragent.com/

**Comment by sejoker** [comment]
I can confirm this user-agent should be using Mobile variant in cache. It's a mystery to me why cache purging doesn't work from your side.

**Comment by DDKL** [comment]
STILL NOT WORKING. WE ARE PAYING YOU THOUSANDS AND YOU HAVE YET TO FIX THIS PROBLEM. VERY FRUSTRATING!!!!!!!!
